name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, "1.90.0"]
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cargo fmt check
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Run tests (debug)
        run: cargo test --all-features

      - name: Run tests (release)
        run: cargo test --release --all-features

      - name: Build docs
        run: cargo doc --no-deps

      - name: cargo-audit
        uses: actions-rs/audit-check@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: cargo-deny
        run: |
          cargo install cargo-deny || true
          cargo deny check
